default_platform(:ios)

platform :ios do
  desc "Description of what the lane does"
  lane :build_lane do
    # swiftlint()
    gym(
    scheme: "FlickerTestApi",
    skip_codesigning: true,
    skip_package_ipa: true
    )
  end
end
